name: 🎨 Storybook

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  storybook:
    name: 🎨 Storybook Build & Deploy to GH Pages
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build Storybook
        run: SKIP_ENV_VALIDATION=true npm run sb:build

      - name: Upload Storybook
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
